### ISSUE TITLE
`join()` type mismatch

### ISSUE THREAD

**Issue by golota60** [4Catalyzer/spa-routing#2]
@jquense I think there's a type mismatch, as this usage is not working
 https://github.com/4Catalyzer/spa-routing/blob/fed3a78190df8d7c3c09b7756dede22be64b7ac4/src/index.ts#L30
<img width="984" alt="image" src="https://user-images.githubusercontent.com/37072867/121894448-6f4e1300-cd1f-11eb-9818-b00ff4d2926c.png">

**Comment by golota60** [comment]
I'll open a WIP pr later, proposing some changes

**Comment by jquense** [comment]
Whoops that comment is wrong. Updated the doc comments to be more accurate
